quarkus.rest-client.blockchain-node.url=https://ethereum-rpc.publicnode.com
#quarkus.hibernate-orm.enabled=false


quarkus.container-image.name=quarkus/block_publisher
quarkus.container-image.tag=quarkus/block_publisher
quarkus.container-image.image=quarkus/block_publisher

#quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.datasource.db-kind=mariadb
quarkus.datasource.jdbc.url=jdbc:mariadb://${datasource.host}/block_publisher
quarkus.datasource.username=block_publisher_user
quarkus.datasource.password=djaUIwwxrZg9TlxSgVNgkZnMoIRlw5vAbhHcnSq7jD7gGs4h4q
datasource.host=localhost:3307

quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.acquisition-timeout=10000


app.scanner.block.job.every.expr=10s
app.scanner.block.batch.size=5